### ISSUE TITLE
Javadoc errors

### ISSUE THREAD

**Issue by klaushauschild1984** [klaushauschild1984/selenium-toys#7]
It's not a huge problem but clutters the build log every time. There are relatively many javadoc errors and warning:

```2 errors
4 warnings
[ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:55: warning: no @param for method
  public void after(final Method method, final boolean hasFailure) {
              ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:55: warning: no @param for hasFailure
  public void after(final Method method, final boolean hasFailure) {
              ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:30: warning: no @param for method
  protected void before(final Method method) {
                 ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:69: warning: no @return
  protected WebDriver getWebDriver() {
                      ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/Webdriver.java:13: error: self-closing element not allowed
 * implementation for web tests.<br/>
                                ^
 * {@link WebdriverFactory} implementation for Google Chrome using the {@link ChromeDriver}.<br />
                                                                                            ^
Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
Refer to the generated Javadoc files in '/home/travis/build/klaushauschild1984/selenium-toys/target/apidocs' dir.
org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:55: warning: no @param for method
  public void after(final Method method, final boolean hasFailure) {
              ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:55: warning: no @param for hasFailure
  public void after(final Method method, final boolean hasFailure) {
              ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:30: warning: no @param for method
  protected void before(final Method method) {
                 ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/SeleniumTests.java:69: warning: no @return
  protected WebDriver getWebDriver() {
                      ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/Webdriver.java:13: error: self-closing element not allowed
 * implementation for web tests.<br/>
                                ^
/home/travis/build/klaushauschild1984/selenium-toys/src/main/java/org/openqa/selenium/toys/factory/chrome/ChromeWebdriverFactory.java:26: error: self-closing element not allowed
 * {@link WebdriverFactory} implementation for Google Chrome using the {@link ChromeDriver}.<br />
                                                                                            ^
Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
Refer to the generated Javadoc files in '/home/travis/build/klaushauschild1984/selenium-toys/target/apidocs' dir.
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5075)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2093)
	at org.apache.maven.plugins.javadoc.JavadocJar.doExecute(JavadocJar.java:188)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute(AbstractJavadocMojo.java:1889)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Building jar: /home/travis/build/klaushauschild1984/selenium-toys/target/selenium-toys-1.0-SNAPSHOT-javadoc.jar

Fix them!

**Comment by Kh1ng** [comment]
Hi I'd still like to work on this after getting some feedback from my PR. I am just new and it is a lot to understand and document but I would like to learn.

**Comment by klaushauschild1984** [comment]
The thing is this issue does not contain the full story.
First, all of the Javadoc errors should be avoided to let the build pass. But second, this should not be achieved by adding nonsense or empty documentation. The added Javadoc should describe the part where it is added to.

**Comment by Kh1ng** [comment]
Yes, I've been reading about some parts I'm unfamiliar with and working on the documentation, not just placeholders or "nonsense." I've gotten a little busy with school starting again but learning a lot so far. I'm planning to keep working on it if that's okay. Thanks for the opportunity.

**Comment by klaushauschild1984** [comment]
No problem.
Depending on what you want to contribute I would like to recommend some more active repositories by me:
https://github.com/xommaterials/jhac
https://github.com/klaushauschild1984/node-nes
https://github.com/klaushauschild1984/gml-tracer
https://github.com/klaushauschild1984/java-natives

Selenium Toys were relevant when I introduced them. Right now was not much interest from others it faded into not being relevant anymore and there are better alternatives like Cypress or so.
