### ISSUE TITLE
IIO Can't read input file!

### ISSUE THREAD

**Issue by klaushauschild1984** [klaushauschild1984/selenium-toys#8]
https://travis-ci.org/klaushauschild1984/selenium-toys/builds/308708797 fails because the ImageIO can not read the input files.

```compareDifferentTest(org.openqa.selenium.toys.ScreenshotComparatorTest)  Time elapsed: 0.044 sec  <<< FAILURE!
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at org.openqa.selenium.toys.ScreenshotComparatorTest.compareDifferentTest(ScreenshotComparatorTest.java:36)
compareIdenticalTest(org.openqa.selenium.toys.ScreenshotComparatorTest)  Time elapsed: 0.001 sec  <<< FAILURE!
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at org.openqa.selenium.toys.ScreenshotComparatorTest.compareIdenticalTest(ScreenshotComparatorTest.java:50)

**Comment by klaushauschild1984** [comment]
Fixed
